#!/bin/bash

if [ "$ANYCABLE_DEPLOYMENT" == "true" ]; then
  bundle exec anycable --server-command="anycable-go" -r ./anycable.rb
else
  bundle exec puma -e production -p $PORT -w $WEB_CONCURRENCY --preload
fi
