#!/bin/bash

if [ "$ANYCABLE_DEPLOYMENT" == "true" ]; then
  bundle exec anycable --server-command="anycable-go" -r ./anycable.rb --rpc-host="127.0.0.1:50051"
else
  bundle exec puma -e production -p $PORT -w $WEB_CONCURRENCY --preload
fi
